global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:

scrape_configs:

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd-exporter:9102']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
    - action: labeldrop
      regex: instance

    - target_label: service
      replacement: "charmhub-io"
    - target_label: service_name
      replacement: "charmhub-io"

  - job_name: 'metrics-collector'
    static_configs:
      - targets: ['metrics-collector:8000']
    scrape_interval: 60s
    metrics_path: /metrics
    relabel_configs:
    - target_label: service
      replacement: "charmhub-metrics"
    - target_label: service_name
      replacement: "charmhub-metrics"