name: Run linkchecker on site

on:
  schedule:
    - cron:  '0 14 * * 1'

jobs:
  run-linkchecker:
    if: github.repository == 'canonical-web-and-design/charmhub.io'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
      - uses: actions/checkout@v4

      - name: Install linkchecker
        run: sudo pip install LinkChecker

      - name: Run linkchecker
        run: linkchecker --ignore-url "http://localhost*" --ignore-url "https://assets.ubuntu.com$" --check-extern --no-warnings https://charmhub.io

      - name: Send message on failure
        if: failure()
        run: curl -X POST -F "workflow=${GITHUB_WORKFLOW}" -F "repo_name=${GITHUB_REPOSITORY}" -F "action_id=${GITHUB_RUN_ID}" ${{ secrets.BOT_URL }}?room=%23web-team
